import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/288_gt_sauber_mercedes.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_16.geometry}
					material={materials.glass_light}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_17.geometry}
					material={materials.glass_turn}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_18.geometry}
					material={materials.glass_wind_dark}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_19.geometry}
					material={materials.grip}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_20.geometry}
					material={materials.mirror}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_22.geometry}
					material={materials.glass_wind}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_27.geometry}
					material={materials.reflector}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_34.geometry}
					material={materials.shade}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_37.geometry}
					material={materials.stop_glass}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_3.geometry}
					material={materials["61_l"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_26.geometry}
					material={materials.red_rubber}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_45.geometry}
					material={materials.light1}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4.geometry}
					material={materials["61_r"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_7.geometry}
					material={materials.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_6.geometry}
					material={materials.bilcas_l}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5.geometry}
					material={materials.material_5}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_8.geometry}
					material={materials.bilcas_r}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_11.geometry}
					material={materials.brakes_disk}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_2.geometry}
					material={materials["600v"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_23.geometry}
					material={materials.pilot_l}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_24.geometry}
					material={materials.pilot_r}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_14.geometry}
					material={materials.door_l}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_15.geometry}
					material={materials.door_r}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_25.geometry}
					material={materials.powered}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_29.geometry}
					material={materials.plastic}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_33.geometry}
					material={materials.sauber_mercedes}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_30.geometry}
					material={materials.rim_front}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_35.geometry}
					material={materials.shadow}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_36.geometry}
					material={materials.sticker_michelin_l}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_9.geometry}
					material={materials.black}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_38.geometry}
					material={materials.sticker_michelin_r}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_28.geometry}
					material={materials.retro}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_21.geometry}
					material={materials.paint}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_32.geometry}
					material={materials.rim_rear}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_13.geometry}
					material={materials.carbon2}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_41.geometry}
					material={materials.wht_plastic}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_42.geometry}
					material={materials.wing}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_10.geometry}
					material={materials.brakes}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_43.geometry}
					material={materials.alum}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_44.geometry}
					material={materials.alum}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_12.geometry}
					material={materials.carbon}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_31.geometry}
					material={materials.rubber}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_40.geometry}
					material={materials.tire}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_39.geometry}
					material={materials.tire_side}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/288_gt_sauber_mercedes.glb");
